---

- name: Ensure GRUB serial console enabled config
  become: yes
  blockinfile:
    block: |
      GRUB_TERMINAL="serial console gfxterm vga_text"
      GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
    path: /etc/default/grub

- name: Ensure GRUB passes systemd serial tty activation to linux kernel config
  become: yes
  lineinfile:
    path: /etc/default/grub
    line: |
      GRUB_CMDLINE_LINUX="console=tty0 console=lp0 console=ttyS0"
    regexp: '^GRUB_CMDLINE_LINUX=""'
    state: present
    
- name: Ensure updated GRUB
  become: yes
  shell: update-grub

- name: Create serial-getty@ttyS0.service.d
  become: yes
  file:
    path: "/etc/systemd/system/serial-getty@ttyS0.service.d"
    owner: root
    group: root
    state: directory
    mode: '0775'


- name: Create serial-getty@ttyS0.service.d override to enable root auto login
  become: yes
  copy:
    dest: "/etc/systemd/system/serial-getty@ttyS0.service.d/override.conf"
    content: |
      ExecStart=
      ExecStart=-/sbin/agetty -a root --noclear %I $TERM
