---
- name: Ensure blog.netsoc.co Docker Container
  become: yes
  docker_stack:
    state: present
    name: blog_netsoc_co
    #with_registry_auth: true
    compose:
      - version: "3.7"
        services:
          server:
            image: docker.netsoc.co/public/blog.netsoc.co:latest
            networks:
              traefik:
            environment:
              BASE_URL: "https://blog.netsoc.co/"
            deploy:
              mode: global
              placement:
                constraints:
                  - node.hostname == {{ inventory_hostname }}
                preferences:
                  - spread: node.id
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.blog_netsoc_co.rule=Host(`blog.netsoc.co`)"
                - "traefik.http.routers.blog_netsoc_co.entrypoints=web-secure"
                - "traefik.http.routers.blog_netsoc_co.tls.certResolver=letsencrypt"
                - "traefik.http.services.blog_netsoc_co-service.loadbalancer.server.port=80"
                - "traefik.http.routers.blog_netsoc_co.service=blog_netsoc_co-service"
                - "traefik.docker.network=traefik"
              restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5
        networks:
          traefik:
              external: true
              name: traefik