---
- name: Ensure Kibana
  become: yes
  docker_stack:
    state: present
    name: kibana
    compose:
      - version: '3.5'
        networks:
          traefik:
            external: true
          elasticsearch:
            external: true
        services:
          server:
            image: kibana:7.5.1
            container_name: kibana
            environment:
              ELASTICSEARCH_HOSTS: http://elasticsearch:9200
            networks:
              - elasticsearch
              - traefik
            deploy:
              mode: replicated
              replicas: 1
              restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.kibana.entrypoints=web-secure"
                - "traefik.http.routers.kibana.rule=Host(`logs.netsoc.dev`)"
                - "traefik.http.routers.kibana.tls.certResolver=letsencrypt"
                - "traefik.http.routers.kibana.service=kibana-service"
                - "traefik.http.services.kibana-service.loadbalancer.server.port=5601"
                - "traefik.docker.network=traefik"
                - "traefik.http.middlewares.kibana-auth.basicauth.users={{ kibana_basic_auth }}"
                - "traefik.http.routers.kibana.middlewares=kibana-auth@docker"