---
  - name: Get current mounted Secret Engines
    uri:
      url: "{{ hashivault_url }}/v1/sys/mounts"
      headers:
        X-Vault-Token: "{{ hashivault_root_token }}"
      method: GET
      return_content: yes
    register: engines
      
  - name: Enable KV Engine at discord/
    when: ('discord/' not in engines.json)
    uri:
      url: "{{ hashivault_url }}/v1/sys/mounts/discord"
      headers:
        X-Vault-Token: "{{ hashivault_root_token }}"
      method: POST
      body_format: json
      status_code: [204]
      body:
        type: kv
        version: "2"

  - name: Push Discord secrets to Hashicorp Vault
    uri:
      url: "{{ hashivault_url }}/v1/discord/sysadmins_webhook"
      headers:
        X-Vault-Token: "{{ hashivault_root_token }}"
      method: PUT
      body_format: json
      status_code: [204]
      body:
        discord_webhook_id: "{{ discord_webhook_id }}"
        discord_webhook_token: "{{ discord_webhook_token }}"
  
  