---
- name: Set vm.max_map_count sysctl
  become: yes
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present

- name: Ensure /netsoc/docker-data/elasticsearch created with 0700
  become: yes
  file:
    path: /netsoc/docker-data/elasticsearch
    owner: netsoc
    group: netsoc
    mode: 0777
    state: directory

- name: Ensure Elasticsearch network
  become: yes
  docker_network:
    name: elasticsearch
    driver: overlay
    attachable: yes

- name: Ensure elasticsearch
  become: yes
  docker_stack:
    state: present
    name: elasticsearch
    compose:
      - version: '3.7'
        networks:
          traefik:
            external: true
          elasticsearch:
            external: true
        services:
          server:
            image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
            container_name: elasticsearch
            volumes:
              - /netsoc/docker-data/elasticsearch:/usr/share/elasticsearch/data
            environment:
              discovery.type: single-node
              xpack.security.enabled: 'false'
              xpack.ml.enabled: 'false'
            networks:
              traefik:
              elasticsearch:
                aliases:
                  - elasticsearch
            ulimits:
              nofile:
                soft: 122880
                hard: 122880              
            deploy:
              mode: global
              placement:
                constraints:
                  - node.role == manager
                  - node.hostname == {{ inventory_hostname }}
              restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.elasticsearch.entrypoints=web-secure"
                - "traefik.http.routers.elasticsearch.rule=Host(`es.netsoc.co`)"
                - "traefik.http.routers.elasticsearch.tls.certResolver=letsencrypt"
                - "traefik.http.routers.elasticsearch.service=elasticsearch-service"
                - "traefik.http.services.elasticsearch-service.loadbalancer.server.port=9200"
                - "traefik.docker.network=traefik"
                - "traefik.http.middlewares.elasticsearch-auth.basicauth.users={{ elasticsearch_basic_auth }}"
                - "traefik.http.routers.elasticsearch.middlewares=kibana-auth@docker"